export const categories = [
  { table: "countries", name: "Países", columns: {  } },
  { table: "states", name: "Estados" },
  { table: "Códigos Postales", name: "Códigos Postales" },
  { table: "countries", name: "Ciudades" },
  { table: "countries", name: "Empresas" },
  { table: "countries", name: "Niveles de Inclusión" },
  { table: "countries", name: "Niveles de Instrucción" },
  { table: "countries", name: "Ubicaciones Organizacionales" },
  { table: "countries", name: "Tipos de Organización" },
  { table: "countries", name: "Estructura Organizativa" },
  { table: "countries", name: "Proyecto" },
  { table: "countries", name: "Sexo" },
  { table: "countries", name: "Estado Civil" },
  { table: "countries", name: "Área de Conocimiento" },
  { table: "countries", name: "Área Organizacional" },
  { table: "countries", name: "Roles" },
  { table: "countries", name: "Cargos" },
  { table: "countries", name: "Capas Organizacionales" },
  { table: "countries", name: "Estados de Alfabetización Tecnológica" },
  { table: "countries", name: "Niveles de Atribución" },
  { table: "countries", name: "Profesiones" },
  { table: "countries", name: "Grados Laborales" },
  { table: "countries", name: "Tipos de Contratación" },
  { table: "countries", name: "Carga Horaria" },
  { table: "countries", name: "Modalidad de Trabajo" },
  { table: "countries", name: "Relación Laboral" },
  { table: "countries", name: "Procesos Organizacionales" },
  { table: "countries", name: "Emosiones Básicas" },
  { table: "countries", name: "Emosiones Derivadas" },
  { table: "countries", name: "Categorias de Encuestas" },
  { table: "countries", name: "Subcategorias de Encuestas" },
  { table: "countries", name: "Preguntas" },
  { table: "countries", name: "Rangos Gerenciales" },
  { table: "countries", name: "Tipos de Parámetros Culturales" },
  { table: "countries", name: "Parámetros Culturales" },
  { table: "countries", name: "Modelos de Aprensizaje" },
  { table: "countries", name: "Estilos de Liderazgo" },
  { table: "countries", name: "Categorías de Referentes" },
  { table: "countries", name: "Tipos de Percepción del Personal" },
  { table: "countries", name: "Estados de Ánimo" },
  { table: "countries", name: "Involucrados" }
];